server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
my-data:
  mapVaccine:
    HepB: {keyName: HepB,des: 乙肝疫苗,accinationMonthAge: [1,2,0,0,0,0,3,0,0,0,0] ,state: true}
    BCG: {keyName: BCG,des: 卡介疫苗,accinationMonthAge: [0] ,state: true}
    IPV: {keyName: IPV,des: 脊灰灭活疫苗,accinationMonthAge: [2], state: true}
    OPV: {keyName: OPV,des: 脊灰减毒活疫苗,accinationMonthAge: [2,3,18],state: true}
    DTaP: {keyName: DTaP,des: 百白破疫苗,accinationMonthAge: [0,0,0,1,2,3],state: true}
    DT: {keyName: DT,des: 白破疫苗,accinationMonthAge: [],state: true}